import { jidNormalizedUser } from "@whiskeysockets/baileys";
import { loadCommands, getCommand, getCommandsByCategory, getAllCommands } from "./command-loader.js";
import { replyWithPresence } from "./response.js";
import { formatResponse, formatError } from "./format.js";

// Cache to keep track of bot-sent message IDs across sessions to avoid infinite loops
const sentMsgIds = new Set();

function getText(message) {
  const m = message.message;
  if (!m) return "";

  return (
    m.conversation ||
    m.extendedTextMessage?.text ||
    m.imageMessage?.caption ||
    m.videoMessage?.caption ||
    ""
  ).trim();
}

/**
 * Normalizes JID to remove device specifiers.
 */
function cleanJid(jid) {
  if (!jid) return "";
  return jidNormalizedUser(jid);
}

/**
 * Check sender permissions in group context.
 */
async function checkPermissions(sock, remoteJid, senderJid) {
  let isGroupAdmin = false;
  let isBotAdmin = false;

  try {
    const groupMeta = await sock.groupMetadata(remoteJid);
    const participants = groupMeta.participants || [];
    const botJid = cleanJid(sock.user?.id);
    const userJid = cleanJid(senderJid);

    const senderParticipant = participants.find(p => cleanJid(p.id) === userJid);
    if (senderParticipant?.admin === "admin" || senderParticipant?.admin === "superadmin") {
      isGroupAdmin = true;
    }

    const botParticipant = participants.find(p => cleanJid(p.id) === botJid);
    if (botParticipant?.admin === "admin" || botParticipant?.admin === "superadmin") {
      isBotAdmin = true;
    }
  } catch (err) {
    // Unable to fetch metadata or not in group
  }

  return { isGroupAdmin, isBotAdmin };
}

export async function handleMessage(sock, message, config) {
  if (!message?.message) return;

  const msgId = message.key?.id;

  // 1. INFINITE LOOP PROTECTION: If this message ID was generated by the bot itself, ignore.
  if (msgId && sentMsgIds.has(msgId)) {
    return;
  }

  const remoteJid = message.key.remoteJid;
  const isGroup = remoteJid?.endsWith("@g.us");
  const botUserJid = cleanJid(sock.user?.id);
  const senderJid = cleanJid(message.key.participant || remoteJid);

  // 2. FROM-ME & SELF-CHAT LOGIC:
  // - Other user -> Bot (key.fromMe = false) => ALLOW
  // - Owner -> Bot in group/private (key.fromMe = false or true depending on user identity) => ALLOW
  // - Owner -> Self Chat ("Message yourself" where remoteJid === botUserJid) => ALLOW
  // - Automatic bot broadcast/echoes (already filtered by sentMsgIds).

  const text = getText(message);
  if (!text.startsWith(config.prefix)) return;

  const parts = text.slice(config.prefix.length).trim().split(/\s+/);
  const commandName = (parts.shift() || "").toLowerCase();
  if (!commandName) return;

  const { commandMap } = await loadCommands();
  const command = getCommand(commandName);

  if (!command) return;

  // Measure network/message receive timestamp to now
  const msgTimestamp = (message.messageTimestamp ? Number(message.messageTimestamp) * 1000 : Date.now());
  const receiveLatency = Math.max(0, Date.now() - msgTimestamp);

  // Measure command execution time
  const startTime = performance.now();

  // Helper reply wrapper
  const reply = async (content, options = {}) => {
    return replyWithPresence(sock, remoteJid, content, { quoted: message, ...options }, sentMsgIds);
  };

  // Group-only check
  if (command.groupOnly && !isGroup) {
    await reply(formatResponse("This command can only be used inside a WhatsApp group.", "GROUP"));
    return;
  }

  // Owner-only check
  const isOwner = senderJid.includes(config.owner) || (botUserJid && senderJid === botUserJid);
  if (command.ownerOnly && !isOwner) {
    await reply(formatError("This command is restricted to the bot owner.", "Access Denied"));
    return;
  }

  // Admin checks for group commands
  if (isGroup && (command.adminOnly || command.botAdminRequired)) {
    const { isGroupAdmin, isBotAdmin } = await checkPermissions(sock, remoteJid, senderJid);

    if (command.adminOnly && !isGroupAdmin && !isOwner) {
      await reply(formatError("This command requires group administrator privileges.", "Admin Required"));
      return;
    }

    if (command.botAdminRequired && !isBotAdmin) {
      await reply(formatError("Voltra Mini needs to be a group admin to execute this action.", "Bot Admin Required"));
      return;
    }
  }

  const args = parts;
  const ctx = {
    sock,
    message,
    args,
    text,
    prefix: config.prefix,
    command: commandName,
    reply,
    isGroup,
    isOwner,
    remoteJid,
    senderJid,
    receiveLatency,
    config,
    getCommandsByCategory,
    getAllCommands
  };

  try {
    await command.execute(ctx);
    const endTime = performance.now();
    const executionTime = Math.round(endTime - startTime);
    console.log(`[Voltra] Executed command: ${commandName} in ${executionTime}ms (Receive latency: ${receiveLatency}ms)`);
  } catch (error) {
    console.error(`[Voltra] Error executing command ${commandName}:`, error);
    await reply(formatError(error.message || "An error occurred while processing the command."));
  }
}
